# Generated by Django 5.1.7 on 2025-08-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
